// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBmI4boIOPLWB4ALgSspzJhYSu-v6FrUTY',
//     appId: '1:945861460008:web:013528374079bd89fef51d',
//     messagingSenderId: '945861460008',
//     projectId: 'ccna-command-hub-2026',
//     authDomain: 'ccna-command-hub-2026.firebaseapp.com',
//     storageBucket: 'ccna-command-hub-2026.firebasestorage.app',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAKfAuRmnvmKfHJ2wxYOyZgbDun90fUOt8',
//     appId: '1:945861460008:android:e5accba8b75dfe38fef51d',
//     messagingSenderId: '945861460008',
//     projectId: 'ccna-command-hub-2026',
//     storageBucket: 'ccna-command-hub-2026.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBwZWnAc4955et0Gk90DLH2snEiXzoOMsk',
//     appId: '1:945861460008:ios:0ef4a21e00ff0bfefef51d',
//     messagingSenderId: '945861460008',
//     projectId: 'ccna-command-hub-2026',
//     storageBucket: 'ccna-command-hub-2026.firebasestorage.app',
//     iosBundleId: 'com.example.ccnaCommandHub',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBwZWnAc4955et0Gk90DLH2snEiXzoOMsk',
//     appId: '1:945861460008:ios:0ef4a21e00ff0bfefef51d',
//     messagingSenderId: '945861460008',
//     projectId: 'ccna-command-hub-2026',
//     storageBucket: 'ccna-command-hub-2026.firebasestorage.app',
//     iosBundleId: 'com.example.ccnaCommandHub',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBmI4boIOPLWB4ALgSspzJhYSu-v6FrUTY',
//     appId: '1:945861460008:web:9473f9361764bc3bfef51d',
//     messagingSenderId: '945861460008',
//     projectId: 'ccna-command-hub-2026',
//     authDomain: 'ccna-command-hub-2026.firebaseapp.com',
//     storageBucket: 'ccna-command-hub-2026.firebasestorage.app',
//   );
// }
